[package]
name = "win_uds"
version = "0.1.5"
edition = "2024"
license-file = "LICENSE"
description = "Windows Unix Domain Socket"
repository = "https://github.com/kouhe3/win_uds"
[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
[dependencies]
futures = "0.3.31"
socket2 = "0.6.1"
[dev-dependencies]
tokio = { version = "1.48", features = ["full"] }
