[package]
name = "win_uds"
version = "0.1.3"
edition = "2024"
license-file = "LICENSE"
description = "Windows Unix Domain Socket"
repository = "https://github.com/kouhe3/win_uds"
[dependencies]
socket2 = "0.6.1"
